<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>org.tahopen</groupId>
  <artifactId>commons-xul</artifactId>
  <packaging>pom</packaging>

  <parent>
    <groupId>org.tahopen</groupId>
    <artifactId>tahopen-drianmon-parent-pom</artifactId>
    <version>0.1.0.0-SNAPSHOT</version>
  </parent>

  <name>Tahopen Commons Xul</name>
  <url>http://www.tahopen.org</url>
  <description>Library XUL the Tahopen ecosystem.</description>

  <scm>
    <connection>scm:git:git://github.com/tahopen/tahopen-commons-xul.git</connection>
    <developerConnection>scm:git:git@github.com:tahopen/tahopen-commons-xul.git</developerConnection>
    <url>https://github.com/tahopen/tahopen-commons-xul</url>
</scm>  
  
  <licenses>
    <license>
      <name>GNU Lesser General Public License, Version 2.1</name>
      <url>https://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt</url>
      <distribution>repo</distribution>
    </license>
  </licenses>

  <modules>
    <module>core</module>
    <module>html</module>
    <module>swing</module>
    <module>gwt</module>
    <module>swt</module>
  </modules>

  <properties>
    <license.licenseName>lgpl_v2_1</license.licenseName>
    <mockito-core.version>4.11.0</mockito-core.version>
  </properties>

  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>commons-collections</groupId>
        <artifactId>commons-collections</artifactId>
        <version>3.2.2</version>
      </dependency>
    </dependencies>
  </dependencyManagement>

  <developers>

    <developer>
      <id>marciojv</id>
      <name>Marcio Junior Vieira</name>
      <email>marcio@tahopen.org</email>
    </developer>

  </developers>
  
  <build>
    <plugins>
       
      <!-- Generate java docs -->
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-javadoc-plugin</artifactId>
        <version>3.2.0</version>
        <executions>
          <execution>
            <goals>
              <goal>jar</goal>
            </goals>
          </execution>
        </executions>
      </plugin>

      <!-- sign key gpg--> 
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-gpg-plugin</artifactId>
        <version>3.0.1</version>
        <executions>
          <execution>
            <goals>
              <goal>sign</goal>
            </goals>
          </execution>
        </executions>
      </plugin>

      <!-- publish to Maven Central --> 
      <plugin>
         <groupId>org.sonatype.central</groupId>
         <artifactId>central-publishing-maven-plugin</artifactId>
         <version>0.6.0</version>
         <extensions>true</extensions>
         <configuration>
           <publishingServerId>maven-central-snapshots</publishingServerId>
         </configuration>
      </plugin>    

    </plugins>
  </build>

  <distributionManagement>

    <repository>
      <id>ossrh</id>
      <url>https://oss.sonatype.org/service/local/staging/deploy/maven2/</url>
    </repository>
    
    <snapshotRepository>
      <id>ossrh</id>
      <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
    </snapshotRepository>
    
  </distributionManagement>
</project>
